import type { Metadata } from "next";
import { Sour_Gummy } from "next/font/google";
import "./globals.css";

const sourGummy = Sour_Gummy({
  weight: ["400", "700"], // Adjust weights as needed
  subsets: ["latin"], // Choose subsets as per your requirement
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${sourGummy.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
